num_boids: 50
fly_mid_scale: 0.01
fly_away_condition: 100
speed_match_condition: 10000
speed_match_scale: 0.125

# Initial Parameters
x_min: -450.0
x_max: 50.0
y_min: 300.0
y_max: 600.0
vx_min: 0.0
vx_max: 10.0
vy_min: -20
vy_max: 20

